# Generated by Django 6.0.1 on 2026-01-14 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('grade_level', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_cards/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grades_data', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_platform.student')),
            ],
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_careers', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('areas_for_improvement', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_platform.reportcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_platform.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_platform.student')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='scripts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_topics', models.JSONField(blank=True, default=list)),
                ('challenging_topics', models.JSONField(blank=True, default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_platform.student')),
            ],
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_platform.uploadedscript')),
            ],
        ),
    ]
