# Generated by Django 6.0.1 on 2026-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedscript',
            name='grade_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedscript',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
