# Generated by Django 6.0.1 on 2026-02-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_platform', '0002_uploadedscript_grade_level_uploadedscript_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
